config:
  solc: "0.8.28"
  framework: "hardhat"
  framework_version: "^2.26.3"
  node_version: "18"
  package_manager: "bun"
  package_manager_version: "^1.2.19"
environment:
  IS_SLITHER: true
tasks:
  install-dependencies:
    - bun install
  pre-scan:
    - bunx hardhat compile