version: v2

config:
  contracts:
    evm:
      enabled: true
      solc: "0.8.28"
      framework: "hardhat"
      framework-version: "^2.26.3"
      node-version: "18"
      package-manager: "bun"
      package-manager-version: "^1.2.19"
      excluded-paths:
        - "contracts/test/**"
        - "contracts/mocks/**"
environment:
  IS_SLITHER: true
tasks:
  install-dependencies:
    - bun install
  pre-scan:
    - bunx hardhat compile